name: Linting
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: pnpm
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
