name: Create and publish a Docker image

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 23

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- STOCK ---

      - name: Extract metadata (tags, labels) for Docker
        id: metastock
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/Nathan-LG/stock.crf

      - name: Build and push Docker image for stock.crf
        id: pushstock
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: apps/stock/Dockerfile
          push: true
          tags: ${{ steps.metastock.outputs.tags }}
          labels: ${{ steps.metastock.outputs.labels }}
          build-args: |
            GIT_TAG=${{ github.ref_name }}
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/Nathan-LG/stock.crf
          subject-digest: ${{ steps.pushstock.outputs.digest }}
          push-to-registry: true

      # --- AGENDA ---

      - name: Extract metadata (tags, labels) for Docker
        id: metaagenda
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/Nathan-LG/agenda.crf

      - name: Build and push Docker image for agenda.crf
        id: pushagenda
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: apps/agenda/Dockerfile
          push: true
          tags: ${{ steps.metaagenda.outputs.tags }}
          labels: ${{ steps.metaagenda.outputs.labels }}
          build-args: |
            GIT_TAG=${{ github.ref_name }}
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/Nathan-LG/agenda.crf
          subject-digest: ${{ steps.pushagenda.outputs.digest }}
          push-to-registry: true
